title: "Manuel Reithuber's Blog"
author: Manuel Reithuber
description: > # this means to ignore newlines until "baseurl:"
  whatever's on my mind
baseurl: "" # the subpath of your site, e.g. /blog
url: http://manuel.reithuber.net
twitter_username: mreithub
github_username:  mreithub

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

