title: "Manuel Reithuber's Blog"
author: Manuel Reithuber
description: > # this means to ignore newlines until "baseurl:"
  Manuel Reithuber's private blog
baseurl: "" # the subpath of your site, e.g. /blog
url: http://manuel.reithuber.net
twitter_username: mreithub
github_username:  mreithub

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock


paginate: 10
paginate_path: "page/:num"

excerpt_separator: "<!--snip-->"
